// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * TournamentStatus tracks where a tournament is in its lifecycle. These consts
 * are the canonical set of valid values; tygo turns them into the matching
 * TypeScript string-literal union (the const names must be prefixed with the
 * type name for tygo's enum detection to fire).
 */
export const TournamentStatusSetup = "setup";
export const TournamentStatusGroupStage = "group_stage";
export const TournamentStatusKnockout = "knockout";
export const TournamentStatusComplete = "complete";
export type TournamentStatus = typeof TournamentStatusSetup | typeof TournamentStatusGroupStage | typeof TournamentStatusKnockout | typeof TournamentStatusComplete;
/**
 * MatchStatus tracks whether a single match has been played.
 */
export const MatchStatusPending = "pending";
export const MatchStatusInProgress = "in_progress";
export const MatchStatusComplete = "complete";
export type MatchStatus = typeof MatchStatusPending | typeof MatchStatusInProgress | typeof MatchStatusComplete;
/**
 * MatchStage distinguishes group-stage fixtures from knockout fixtures.
 */
export const MatchStageGroup = "group";
export const MatchStageKnockout = "knockout";
export type MatchStage = typeof MatchStageGroup | typeof MatchStageKnockout;
/**
 * Tournament is the latest tournament's top-level state.
 */
export interface Tournament {
  id: string;
  name: string;
  status: TournamentStatus;
  config: string;
  created_at: string;
}
/**
 * Competitor is a registered player plus their aggregate win/loss record.
 */
export interface Competitor {
  id: string;
  name: string;
  email: string | null;
  ticket_tailor_id: string | null;
  seed: number /* int */ | null;
  group_id: string | null;
  wins: number /* int */;
  losses: number /* int */;
  points: number /* int */;
}
/**
 * RemovedCompetitor is a competitor who has been removed from the tournament;
 * they can be restored from the competitors page.
 */
export interface RemovedCompetitor {
  id: string;
  name: string;
}
/**
 * CompetitorStanding is one row of a group's standings table.
 */
export interface CompetitorStanding {
  id: string;
  name: string;
  played: number /* int */;
  won: number /* int */;
  lost: number /* int */;
  points: number /* int */;
}
/**
 * Group is a draw group with its current standings.
 */
export interface Group {
  id: string;
  name: string;
  competitors: CompetitorStanding[];
}
/**
 * Match is a single fixture in either the group or knockout stage. Player and
 * score fields are nullable because a knockout slot may not be filled yet.
 * Bracket is set for knockout matches only: 1 = main bracket, 2 = consolation.
 */
export interface Match {
  id: string;
  stage: MatchStage;
  group_id: string | null;
  bracket: number /* int */ | null;
  round: number /* int */ | null;
  position: number /* int */ | null;
  player1_id: string | null;
  player1_name: string | null;
  player2_id: string | null;
  player2_name: string | null;
  winner_id: string | null;
  player1_score: number /* int */ | null;
  player2_score: number /* int */ | null;
  status: MatchStatus;
}
/**
 * TicketTailorEvent is one event on the connected Ticket Tailor account,
 * listed so the user can pick which event to import attendees from.
 */
export interface TicketTailorEvent {
  id: string;
  name: string;
}
/**
 * Config reports server-side runtime flags the frontend adapts to. Demo is
 * true when the server was started by `just demo`; the Settings page then
 * pre-fills the built-in demo API credentials if none are saved.
 */
export interface Config {
  demo: boolean;
}
