// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * TournamentStatus tracks where a tournament is in its lifecycle. These consts
 * are the canonical set of values; tygo renders them as a TypeScript
 * string-literal union (names must carry the type prefix for it to detect them).
 */
export const TournamentStatusSetup = "setup";
export const TournamentStatusGroupStage = "group_stage";
export const TournamentStatusKnockout = "knockout";
export const TournamentStatusComplete = "complete";
export type TournamentStatus = typeof TournamentStatusSetup | typeof TournamentStatusGroupStage | typeof TournamentStatusKnockout | typeof TournamentStatusComplete;
/**
 * MatchStatus tracks whether a single match has been played.
 */
export const MatchStatusPending = "pending";
export const MatchStatusInProgress = "in_progress";
export const MatchStatusComplete = "complete";
export type MatchStatus = typeof MatchStatusPending | typeof MatchStatusInProgress | typeof MatchStatusComplete;
/**
 * MatchStage distinguishes group-stage fixtures from knockout fixtures.
 */
export const MatchStageGroup = "group";
export const MatchStageKnockout = "knockout";
export type MatchStage = typeof MatchStageGroup | typeof MatchStageKnockout;
/**
 * Tournament is the latest tournament's top-level state.
 */
export interface Tournament {
  id: string;
  name: string;
  status: TournamentStatus;
  config: string;
  created_at: string;
}
/**
 * Competitor is a registered player plus their aggregate win/loss record.
 */
export interface Competitor {
  id: string;
  name: string;
  email: string | null;
  ticket_tailor_id: string | null;
  seed: number /* int */ | null;
  group_id: string | null;
  wins: number /* int */;
  losses: number /* int */;
  points: number /* int */;
}
/**
 * RemovedCompetitor is a competitor who has been removed from the tournament;
 * they can be restored from the competitors page.
 */
export interface RemovedCompetitor {
  id: string;
  name: string;
}
/**
 * CompetitorStanding is one row of a group's standings table.
 */
export interface CompetitorStanding {
  id: string;
  name: string;
  played: number /* int */;
  won: number /* int */;
  lost: number /* int */;
  points: number /* int */;
}
/**
 * Group is a draw group with its current standings.
 */
export interface Group {
  id: string;
  name: string;
  competitors: CompetitorStanding[];
}
/**
 * Match is a single fixture in either the group or knockout stage. Player and
 * score fields are nullable because a knockout slot may not be filled yet.
 * Bracket is set for knockout matches only: 1 = main bracket, 2 = consolation.
 */
export interface Match {
  id: string;
  stage: MatchStage;
  group_id: string | null;
  group_name: string | null;
  bracket: number /* int */ | null;
  round: number /* int */ | null;
  position: number /* int */ | null;
  player1_id: string | null;
  player1_name: string | null;
  player2_id: string | null;
  player2_name: string | null;
  winner_id: string | null;
  player1_score: number /* int */ | null;
  player2_score: number /* int */ | null;
  status: MatchStatus;
}
/**
 * TieBreak is a tie the ranking rules cannot settle where the order decides who
 * progresses, reported so the organiser can choose. Only outcome-changing ties
 * are raised: players level on points who all qualify anyway keep the order the
 * standings gave them.
 */
export interface TieBreak {
  id: string;
  /**
   * "group" for a tie within one group's standings, or "pool" for one between
   * the next-place finishers of different groups competing for the last few
   * places — those players have never met, so head-to-head cannot help.
   */
  scope: string;
  group_name: string;
  bracket: number /* int */;
  /**
   * 1-based finishing place the tie starts at; for a "pool" tie this is only a
   * position within the pool.
   */
  place: number /* int */;
  /**
   * How many of the tied players take the remaining qualifying places.
   */
  slots: number /* int */;
  points: number /* int */;
  /**
   * Where the players who miss out land, so the organiser can see what they
   * are deciding. A group tie may drop them into the runners-up pool for the
   * same bracket; otherwise they fall to DropsToBracket, which is 0 when there
   * is no bracket below and missing out means not progressing at all.
   */
  drops_to_pool: boolean;
  drops_to_bracket: number /* int */;
  competitors: TieCandidate[];
}
/**
 * TieCandidate is one competitor caught in a TieBreak, with the group-stage
 * record shown alongside their name so the organiser can judge the call.
 */
export interface TieCandidate {
  id: string;
  name: string;
  group_name: string;
  played: number /* int */;
  won: number /* int */;
  points: number /* int */;
}
/**
 * TicketTailorEvent is one event on the connected Ticket Tailor account,
 * listed so the user can pick which event to import attendees from.
 */
export interface TicketTailorEvent {
  id: string;
  name: string;
}
/**
 * Settings are organiser preferences persisted in the database, so they survive
 * restarts and apply wherever the buttons are pressed — the Settings page
 * configures behaviour, the Match History page carries the buttons.
 */
export interface Settings {
  /**
   * Minimum group-stage games per player: the automatic draw sizes groups at
   * MinGroupGames+1, and an uneven remainder makes some groups one player
   * bigger — an extra game, never a shortfall.
   */
  min_group_games: number /* int */;
  /**
   * Fixed group count overriding the automatic sizing (0 = automatic).
   */
  num_groups: number /* int */;
  /**
   * Finishers advancing into each knockout bracket in total: the top places
   * from every group, with the best next-place finishers filling any remainder
   * (16 from 6 groups = top 2 each + the 4 best thirds). Must be a power of
   * two (see advanceTotals) so the bracket fills exactly.
   */
  advance_total: number /* int */;
  /**
   * Put all qualifiers in one bracket rather than splitting into Champion's
   * and Europa leagues.
   */
  single_bracket: boolean;
}
/**
 * Config reports server-side runtime flags the frontend adapts to. Demo is
 * true when the server was started by `just demo`; the Settings page then
 * pre-fills the built-in demo API credentials if none are saved.
 */
export interface Config {
  demo: boolean;
}
